### ISSUE TITLE
Not working SAVE button in one location

### ISSUE THREAD

**Issue by efpek** [pdulvp/jellyfin-qnap#119]
Not working SAVE button in location: Dashboard->Users->Specify_user->Edit this user profile->Display

Any changes within this page could not be saved. In this location is stored limiting movies per page wich is default 100.

Checked in 10.10.1 and 10.10.2 and 10.10.3 in option - Default one, for most of QNAP NAS

**Comment by Oednerich** [comment]
Hi, not sure what caused it but since 10.10.x I had some hiccups in the user profile settings as well when changing themes.
blue radiance background kinda broke and it's just a flat blue instead of what it used to be.
When I changed themes to black and saved and went back again, it was kinda buggy to change to blue, had to try several times, but finally it worked (ended up with black anyway to use finimalism).
It was actually not that bad since I found better themes after some research (https://github.com/tedhinklater/finimalism i.e.)

Since the movies per page limit is on the same page, its also buggy to save.
reset your browser cache, restart jellyfin server, change setting again.
try different browsers or an incognito session if it doesn't work.

I just tested it on my 10.10.3 qnap installation and I can freely change the movie limit per page, so I dont think it's general save issue.
I'm not sure if this is even a qnap-jellyfin issue, but I dont have a non-qnap jellyfin server to test it on right now.

**Comment by efpek** [comment]
> Since the movies per page limit is on the same page, its also buggy to save. reset your browser cache, restart jellyfin server, change setting again. try different browsers or an incognito session if it doesn't work.
> 
It helps - browser cache reset. Thank You
