### ISSUE TITLE
How can I install this?

### ISSUE THREAD

**Issue by sepsol** [pdulvp/jellyfin-qnap#39]
Searched the whole web and repo but couldn't find an answer.

Also, is there any benefit to installing it this way vs the official docker way (via container station)?

**Comment by pdulvp** [comment]
For the installation, In the `App Center` > `Install manually`, then choose the downloaded Qpkg from the releases. I have updated the Readme accordingly.

For the "official docker way (via container station)", as i don't know how to use Container Station, i can't tell, but if it is already installed on your QNAP don't bother by installing it as you will lose your favorites and watched since it will not refer to the same folders or settings.

**Comment by sepsol** [comment]
Thanks for the explanation and updating the readme!
